version: "3"

services:
  sk2server:
    container_name: "sk2-tcp-server"

    build:
      context: server/
      dockerfile: Dockerfile

    ports:
      - "1234:8080"

  sk2client:
    container_name: "sk2-tcp-client"
    build:
      context: client/
      dockerfile: Dockerfile
